---
title: "Color schemes in accordance with the ICAE corporate design"
author: "Claudius Gräbner"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introduction

This package provides some functions that make it easy to create figures in accordance with the corporate design colors of the Institute for Comprehensive Analysis of the Economy (ICAE) at the Johannes Kepler University in Linz.^[More information about the ICAE can be found [here](https://www.jku.at/en/institute-for-comprehensive-analysis-of-the-economy/).]

The package is still under development. Here is just a quick overview over its functions. Note that all exported function already have a complete documentation so you might refer to the help function for more details.

# The palettes
Currently, the package contains the following X palettes:
  
  All of them come with both continuous and discrete versions.

# Using the package

The key functions of the package are `scale_color_icae()` and `scale_fill_icae()`, which allow to control the `color` and `fill` aesthetics in ggplot2 objects respectively. Please note that currently only the application to ggplot2 objects is supported.

## Time series data

If you want to highlight different countries I found the `mixed` palette to be superior:
  
  
## Barplot data
